spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    port: 3638
    host: 10.32.204.19
    timeout: 5000
    lettuce:
      pool:
        # 连接池大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池中的大空闲连接
        max-idle: 8
        # 连接池中的小空闲连接
        min-idle: 0
        # 连接池大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1000
        # 关闭超时时间
        shutdown-timeout: 100
    password: mfga7i3q

